bundle:
  name: hybrid-cache
  version: 0.1.0

modules:
  include:
    - cache:modules/cache-provider-wrapper
    - cache:modules/cache-tool-wrapper
    - cache:modules/cache-store-sqlite
    - cache:modules/cache-store-chroma
    - cache:modules/cache-normalizer
    - cache:modules/embedder-openai

context:
  include:
    - cache:context/hybrid-cache-awareness.md

config:
  cache:
    enabled: true
    metrics:
      enabled: true
    exact:
      ttl: 86400
      max_entries: 50000
    semantic:
      enabled: true
      threshold: 0.90
      embedding:
        provider: openai
        model: text-embedding-3-small
        dimensions: 1536
        batch_size: 32
        timeout_s: 10
        max_retries: 3
        retry_backoff_s: [1, 2, 4]
    storage:
      path: ./cache
